clear all
close all
clc
n=-100:0.8:100;
fs=1;
N=length(n);
f=(-N/2:N/2-1)*fs/N;
x1=cos(0.25*pi*n);
x1f=fftshift(abs(fft(x1,N)/N));
x1d=downsample(x1,3);
x1df=fftshift(abs(fft(x1d,N)/N));
x1e=upsample(x1d,3);
x1ef=fftshift(abs(fft(x1e,N)/N));
x1r=filter(lowpass,x1e);
x1rf=fftshift(abs(fft(x1r,N)/N));
figure(1);
subplot(2,2,1);
plot(f,x1f);
grid on;
xlabel('frequency');
ylabel('X1(f)');
subplot(2,2,2);
plot(f,x1df);
grid on;
xlabel('frequency');
ylabel('X1-downsamling(f)');
subplot(2,2,3);
plot(f,x1ef);
grid on;
xlabel('frequency');
ylabel('X1-upsamling(f)');
subplot(2,2,4);
plot(f,x1rf);
grid on;
xlabel('frequency');
ylabel('X1-output(f)');
x2=cos(0.5*pi*n);
x2f=fftshift(abs(fft(x2,N)/N));
x2d=downsample(x2,3);
x2df=fftshift(abs(fft(x2d,N)/N));
x2e=upsample(x2d,3);
x2ef=fftshift(abs(fft(x2e,N)/N));
x2r=filter(lowpass,x2e);
x2rf=fftshift(abs(fft(x2r,N)/N));
figure(2);
subplot(2,2,1);
plot(f,x2f);
grid on;
xlabel('frequency');
ylabel('X2(f)');
subplot(2,2,2);
plot(f,x2df);
grid on;
xlabel('frequency');
ylabel('X2-downsamling(f)');
subplot(2,2,3);
plot(f,x2ef);
grid on;
xlabel('frequency');
ylabel('X2-upsamling(f)');
subplot(2,2,4);
plot(f,x2rf);
grid on;
xlabel('frequency');
ylabel('X2-output(f)');
x3=8*sinc(0.125*n).^2;
x3f=fftshift(abs(fft(x3,N)/N));
x3d=downsample(x3,3);
x3df=fftshift(abs(fft(x3d,N)/N));
x3e=upsample(x3d,3);
x3ef=fftshift(abs(fft(x3e,N)/N));
x3r=filter(lowpass,x3e);
x3rf=fftshift(abs(fft(x3r,N)/N));
figure(3);
subplot(2,2,1);
plot(f,x3f);
grid on;
xlabel('frequency');
ylabel('X3(f)');
subplot(2,2,2);
plot(f,x3df);
grid on;
xlabel('frequency');
ylabel('X3-downsamling(f)');
subplot(2,2,3);
plot(f,x3ef);
grid on;
xlabel('frequency');
ylabel('X3-upsamling(f)');
subplot(2,2,4);
plot(f,x3rf);
grid on;
xlabel('frequency');
ylabel('X3-output(f)');